// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY1U9-_V0dnt7LL2gmg6L0erYHbS6HkdQ',
    appId: '1:820846566980:web:84adcf9b847b4bbe8e6611',
    messagingSenderId: '820846566980',
    projectId: 'new1-5a89b',
    authDomain: 'new1-5a89b.firebaseapp.com',
    storageBucket: 'new1-5a89b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAyDAsM0Y6NxUSeONPzC5pgiWhmdRcwzU',
    appId: '1:820846566980:android:a418f18262cebd778e6611',
    messagingSenderId: '820846566980',
    projectId: 'new1-5a89b',
    storageBucket: 'new1-5a89b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxd9yggTMLF1dfMNWYgxp35cj-VXC47Wk',
    appId: '1:820846566980:ios:7de08968a990f0758e6611',
    messagingSenderId: '820846566980',
    projectId: 'new1-5a89b',
    storageBucket: 'new1-5a89b.appspot.com',
    iosBundleId: 'com.example.firebaseApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxd9yggTMLF1dfMNWYgxp35cj-VXC47Wk',
    appId: '1:820846566980:ios:08cdc84621c763dc8e6611',
    messagingSenderId: '820846566980',
    projectId: 'new1-5a89b',
    storageBucket: 'new1-5a89b.appspot.com',
    iosBundleId: 'com.example.firebaseApplication1.RunnerTests',
  );
}
